/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseTab: typeof import('./src/components/ChartConfigDialog/BaseTab.vue')['default']
    ChartConfigDialog: typeof import('./src/components/ChartConfigDialog/index.vue')['default']
    ChartPanel: typeof import('./src/components/ChartConfigDialog/ChartPanel.vue')['default']
    ConfigForm: typeof import('./src/components/ChartConfigDialog/ConfigForm.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    MoreConfigTab: typeof import('./src/components/ChartConfigDialog/MoreConfigTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
